name: flutter_instaclone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+9
  flutter_icons: ^1.1.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_storage: ^8.0.0
  firebase_database: ^7.0.1
  cloud_firestore: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf